-- // NEW LIST | GV-280
return {
    -- ====================== Admin ================================
    ["Yolmar_43"] = { Tag = "dyumraisgoodguy", Time = nil, Day = 99999999, Key = "DYHUB-OWNER" },
    ["55555555555555555455"] = { Tag = "oszq_", Time = nil, Day = 111, Key = "DYHUB-nigga" },
    ["Go_Ertadx4"] = { Tag = "Free", Time = "Lifetime", Day = nil, Key = "DYHUB-FREE-UNLIMITED" },
    ["Hanehxo91"] = { Tag = "Free", Time = "Lifetime", Day = nil, Key = "DYHUB-FREE-UNLIMITED" },
    ["XxToxicProxX200550"] = { Tag = "nano_1010.", Time = "Lifetime", Day = nil, Key = "DYHUB-NANO-LIFETIME" },

    -- ====================== Buyer ================================
    ["kagefym"] = { Tag = "itspect", Time = "Lifetime", Day = nil, Key = "DYHUB-ZXCVB-NMLKJ-HGFDS-APOIU-YTREW-LIFETIME" },
    ["Yavib_Aga"] = { Tag = "yavib", Time = "Lifetime", Day = nil, Key = "DYHUB-8JY5A-Q3RTW-IK7OL-FRJL2-IPL7W-LIFETIME" },
    ["10k_langsa"] = { Tag = "idkkkkk0813", Time = "Lifetime", Day = nil, Key = "DYHUB-QWERT-YUIOP-ASDFG-HJKLZ-XCVBN-LIFETIME" },
    ["MeowyBee"] = { Tag = "meowybee", Time = "Lifetime", Day = nil, Key = "DYHUB-4FJ8K-M1N2P-Q7RST-VWXYZ-U6L8F-LIFETIME" },
    ["PauGross0_910"] = { Tag = "lxxx7.", Time = "Lifetime", Day = nil, Key = "DYHUB-ST6IW-0K7WG-L8TWG-2GR5L-MN5O1-LIFETIME" },
    ["stealbf9"] = { Tag = "nzmdlz_97886", Time = "Lifetime", Day = nil, Key = "DYHUB-3WTAB-KU6AG-P9WBA-OI5SA-YEGSY-LIFETIME" },
    ["DjScrew65"] = { Tag = "pizzaman7654", Time = "Lifetime", Day = nil, Key = "DYHUB-HU6SH-9KSN1-L8SHA-YTW5S-NA84A-LIFETIME" },
    ["CinderellaPT"] = { Tag = "_geisha", Time = "Lifetime", Day = nil, Key = "DYHUB-HYWU8-P9AJ3-M7LA9-0UWN3-4HS67-LIFETIME" },
    ["Masayoshi88"] = { Tag = "musashi_0940", Time = "Lifetime", Day = nil, Key = "DYHUB-Pauljames12300" },
    ["Dnoo039"] = { Tag = "meboop90", Time = "Lifetime", Day = nil, Key = "DYHUB-JUYV2-A7OIQ-MJ42P-L8KQW-GD4A3-LIFETIME" },
    ["NeoMitsui"] = { Tag = "silent_erro", Time = "Lifetime", Day = nil, Key = "DYHUB-HUIH6-R3DX6-L9PH5-EW2QD-8H54D-LIFETIME" },
    ["Khalil4258"] = { Tag = "kyoromi_.", Time = "Lifetime", Day = nil, Key = "DYHUB-GS6AV-HY5AF-PKAHE-I7AYW-P9QY5-LIFETIME" },
    ["soytteeo"] = { Tag = "pilot110737", Time = "Lifetime", Day = nil, Key = "DYHUB-P8A6G-LA6HD-NAH7A-N6H7G-T7HB1-LIFETIME" },
    ["Venom120veno"] = { Tag = "66_k0", Time = "Lifetime", Day = nil, Key = "DYHUB-F4AEQ-SR5AF-I4EAD-V5QRA-O8QYA-LIFETIME" },
    ["koreadog4"] = { Tag = "idratherliethantoloseyougirl", Time = "Lifetime", Day = nil, Key = "DYHUB-W3RQ5-Y2BA4-I7QY4-P9AU1-B5W3I-LIFETIME" },
    ["ukatstvc5685"] = { Tag = "earth_12124", Time = "Lifetime", Day = nil, Key = "DYHUB-Q3WRC-O8AYQ-T6ARQ-K5EA4-I76TQ-LIFETIME" },
    ["BabySharkCuteRoblox"] = { Tag = "erenbabysharkyeager", Time = "Lifetime", Day = nil, Key = "DYHUB-KUA5Q-T4QEA-I7TA4-U5RQA-T5RQ3-LIFETIME" },
    ["popj29"] = { Tag = "deathtopias", Time = "Lifetime", Day = nil, Key = "DYHUB-S4QE2-T4WEQ-Y6TW4-I7YA5-Q29IJ-LIFETIME" },
    ["ICERTYUH"] = { Tag = "test_0", Time = "Lifetime", Day = nil, Key = "DYHUB-T3RWQ-O8UA3-PI1IW-Y6WYA-I8QU3-LIFETIME" },
    ["4ny0n3i"] = { Tag = "7he3ni7", Time = "Lifetime", Day = nil, Key = "DYHUB-G5QR3-I7YQ3-U7WY1-E2YF9-R4M0A-LIFETIME" },
    ["Zehnpz"] = { Tag = "unnamed_.0152", Time = "Lifetime", Day = nil, Key = "DYHUB-E3QW4-Y3WRQ-I7YQ4-O2WY1-R5Q3W-LIFETIME" },
    ["gjoopkj9"] = { Tag = "zerex0628", Time = "Lifetime", Day = nil, Key = "DYHUB-Y5RA2-U6TW1-O8WUA-G6QT8-M8NQ5-LIFETIME" },
    ["doremon0258"] = { Tag = "tantran7258", Time = "Lifetime", Day = nil, Key = "DYHUB-Y5WR8-P9UQ4-E4W5U-RQ3WM-V4TW7-LIFETIME" },
    ["Moodeng694"] = { Tag = "koa6871", Time = "Lifetime", Day = nil, Key = "DYHUB-E4QE5-G6RA3-Q2T4S-N7TA4-CA3Q4-LIFETIME" },
    ["nosj3457"] = { Tag = "nonosi12", Time = "Lifetime", Day = nil, Key = "DYHUB-P7R5Q-S3U2T-H6TQ4-C4T6Q-B6A4C-LIFETIME" },
    ["douyin00362"] = { Tag = "bunnyphotos", Time = "Lifetime", Day = nil, Key = "DYHUB-L8JA4-S3U2T-H6TQ4-C4T6Q-S4QT3-LIFETIME" },
    ["Pokeandy42_o"] = { Tag = "andydbandy", Time = "Lifetime", Day = nil, Key = "DYHUB-L8JA4-S3U2T-H6TQ4-C4T6Q-S4QT3-LIFETIME" },
    ["berliando25"] = { Tag = "sayasukaeskrim", Time = "Lifetime", Day = nil, Key = "DYHUB-D5GA3-X3DQ2-N7B4A-L9MY5-V6BR3-LIFETIME" },
    ["klnd40glsd60"] = { Tag = "ekngchaa555555", Time = "Lifetime", Day = nil, Key = "DYHUB-JMY7B-BP5VA-KA7NQ-CH4CP-BX4FQ-LIFETIME" },
    ["Goe9415"] = { Tag = "herysas96_09914", Time = "Lifetime", Day = nil, Key = "DYHUB-KAH6F-MU7A1-L91AD-BG3H9-P9CA3-LIFETIME" },
    ["Zeyss404"] = { Tag = "itsme_joo", Time = "Lifetime", Day = nil, Key = "DYHUB-P9CA3-LAJ29-EQ4TS-BA7NQ-OAI8F-LIFETIME" },
    ["aku4su"] = { Tag = "xpez_", Time = "Lifetime", Day = nil, Key = "DYHUB-N7MI4-VA4CQ-M7NA4-L9MA4-C4DQ3-LIFETIME" },
    ["SumbuI03"] = { Tag = "kingdhoo", Time = "Lifetime", Day = nil, Key = "DYHUB-BA6GQ-JA5VQ-BA7HQ-KA9Q2-BA5VQ-LIFETIME" },
    ["Minirval"] = { Tag = "kama.z", Time = "Lifetime", Day = nil, Key = "DYHUB-XRA3Q-BA6G1-GS6B7-ML8OQ5-CA3Q8-LIFETIME" },
    ["IdgNF23"] = { Tag = "theonlybeamer", Time = "Lifetime", Day = nil, Key = "DYHUB-QA9X2-TM6F4-RL8C3-NZ1Y7-LIFETIME" },
    ["dsny15xnyf23"] = { Tag = "saraheyo4247", Time = "Lifetime", Day = nil, Key = "DYHUB-VG5G2-NAY6G-F4CQ5-UQ8N6-LIFETIME" },
    ["thehyxoncheater"] = { Tag = "h1nrq", Time = "Lifetime", Day = nil, Key = "DYHUB-M8KA9-FA4CQ-JA7NQ-N7BA5-LIFETIME" },
    ["silverkizz"] = { Tag = "ryzeedddd", Time = "Lifetime", Day = nil, Key = "DYHUB-K8MA7-FA4CQ-JA7NQ-N7BA5-LIFETIME" },
    ["Arinchai_81"] = { Tag = "mai_kub55", Time = "Lifetime", Day = nil, Key = "DYHUB-M7NA5-FA4CQ-JA7NQ-N7BA5-LIFETIME" },
    ["KunzaThai"] = { Tag = "tui1558", Time = "Lifetime", Day = nil, Key = "DYHUB-FA4CQ-JA7NQ-N7BA5-DK8M5-LIFETIME" },
    ["saitamasankundes"] = { Tag = "kia1phmtidkii", Time = "Lifetime", Day = nil, Key = "DYHUB-J7NA6-JA7NQ-N7BA5-DK8M5-LIFETIME" },
    ["Xdarkmaster35"] = { Tag = "unkn0wn_death", Time = "Lifetime", Day = nil, Key = "DYHUB-JA7A4-P9MA4-N7BA5-DK8M5-LIFETIME" },
    ["mistorwowka"] = { Tag = "mistorwowka", Time = "Lifetime", Day = nil, Key = "DYHUB-P9MA7-E4VQ5-N7BA5-DK8M5-LIFETIME" },
    ["Max_Jrrrrrr"] = { Tag = "schedule2the", Time = "Lifetime", Day = nil, Key = "DYHUB-N4AF5-E4VQ5-N7BA5-DK8M5-LIFETIME" },
    ["Panakeeee"] = { Tag = "winzx0494", Time = "Lifetime", Day = nil, Key = "DYHUB-P9KA6-E4VQ5-N7BA5-K5GA6-LIFETIME" },
    ["TheRulerOfHavkers"] = { Tag = "trollgespeices1_antifurry", Time = "Lifetime", Day = nil, Key = "DYHUB-U6QB8-E4VQ1-DA5BQ-K5GA6-LIFETIME" },
    ["WEQWES7"] = { Tag = "unsuccessful_dude", Time = "Lifetime", Day = nil, Key = "DYHUB-J7NA4-E4VQ1-S4VQ5-D4CQ5-LIFETIME" },
    ["Kyyyforlieee"] = { Tag = "arssyss", Time = "Lifetime", Day = nil, Key = "DYHUB-J7NA4-S5BQ6-MKY7A-O8NA4-LIFETIME" },
    ["a2i_lowercaseispw"] = { Tag = "h3nry_g4m1ng", Time = "Lifetime", Day = nil, Key = "DYHUB-L9MA7-H7NA6-HA7A5-E4VA6-LIFETIME" },
    ["ggdfggh_5"] = { Tag = "bulucky830", Time = "Lifetime", Day = nil, Key = "DYHUB-G6NA7-H7NA6-M8KA6-P5F2N-LIFETIME" },
    ["syahidhc"] = { Tag = "syahidhc", Time = "Lifetime", Day = nil, Key = "DYHUB-B6NA7-H7NA6-M8KA6-P5F2N-LIFETIME" },
    ["accountac7"] = { Tag = "zeroless2", Time = "Lifetime", Day = nil, Key = "DYHUB-V5L7A-H7NA6-M8KA6-P5F2N-LIFETIME" },
    ["Fail4Me"] = { Tag = "smi.fi", Time = "Lifetime", Day = nil, Key = "DYHUB-V5L7A-H7NA6-EIA73-P5F2N-LIFETIME" },
    ["0engraved"] = { Tag = "01rxedrxosee", Time = "Lifetime", Day = nil, Key = "DYHUB-LAZY" },
    ["loyd3132"] = { Tag = "vortex_260", Time = "Lifetime", Day = nil, Key = "DYHUB-V9L0A-H7NA6-EIA73-P5F2N-LIFETIME" },
    ["TTMEE11"] = { Tag = "pineappl_e.", Time = "Lifetime", Day = nil, Key = "DYHUB-U6QB8-E4VQ5-PA9K8-K5GA6-LIFETIME" },
    ["deathkillerx18"] = { Tag = "yuuwu_", Time = "Lifetime", Day = nil, Key = "DYHUB-J7NA4-H7NA6-MKY7A-Y7NA5-LIFETIME" },
    ["gra_nth"] = { Tag = "granthur", Time = "Lifetime", Day = nil, Key = "DYHUB-U7NP4-H7NA6-MKY7A-Y7NA5-LIFETIME" },
    ["BloodyM4Y4"] = { Tag = "bober_official_bksf", Time = "Lifetime", Day = nil, Key = "DYHUB-U7NP4-D4V5P-MKY7A-Y7NA5-LIFETIME" },
    ["killstreakplayer4"] = { Tag = "mr_guy0986", Time = "Lifetime", Day = nil, Key = "DYHUB-B1M7A-L8MAG-Y50A6-P9MA6-LIFETIME" },
    ["tonypladueu"] = { Tag = "deymongameover", Time = "Lifetime", Day = nil, Key = "DYHUB-BL97O-L8MRG-Y50A6-T6B7N-LIFETIME" },
    ["Jordy172638"] = { Tag = "xcxkll_60833", Time = "Lifetime", Day = nil, Key = "DYHUB-PD0L4-PR87B-T0BQ4-U8MA6-LIFETIME" },
    ["Defracker"] = { Tag = "defracker_", Time = "Lifetime", Day = nil, Key = "DYHUB-B1M7A-K8MAC-Y5BA6-P9MA6-LIFETIME" },
    ["alyciaracquel"] = { Tag = ".xlunatic.", Time = "Lifetime", Day = nil, Key = "DYHUB-BP97A-L8MLG-Y50A6-P8MA6-LIFETIME" },
    ["Z_MRSAONO"] = { Tag = "potae0001", Time = "Lifetime", Day = nil, Key = "DYHUB-BL97O-L8MRG-Y50A6-P8MA6-LIFETIME" },
    ["Rogo816"] = { Tag = "yogager_2_09143", Time = "Lifetime", Day = nil, Key = "DYHUB-BL17O-L8MRG-Y50A6-P8MA6-LIFETIME" },
    ["holainure"] = { Tag = "duxuup", Time = "Lifetime", Day = nil, Key = "DYHUB-FL17O-L8MRG-Y10A6-P1MA6-LIFETIME" },
    ["wdawdsaweresfdxd"] = { Tag = "o9o693254", Time = "Lifetime", Day = nil, Key = "DYHUB-FL179-L8MRG-Y10A6-P1MA6-LIFETIME" },
    ["jamjankun"] = { Tag = "flowerfieldstri", Time = "Lifetime", Day = nil, Key = "DYHUB-FL1K9-U8LRG-Y10A6-P1MA6-LIFETIME" },
    ["jvchgnbngiscool"] = { Tag = "jvchgnbng_", Time = "Lifetime", Day = nil, Key = "DYHUB-DL1K9-F8LRG-Y10A6-Y1MA6-LIFETIME" },
    ["w11o26"] = { Tag = "dimitri1274", Time = "Lifetime", Day = nil, Key = "DYHUB-DL1K9-F8LRG-Y1JA6-Y1MA5-LIFETIME" },
    ["jameboba09"] = { Tag = "bruh_bruh1999", Time = "Lifetime", Day = nil, Key = "DYHUB-JL1K9-I8LRG-Y1JA6-P1MA5-LIFETIME" },
    ["oak_1257"] = { Tag = "oak1267_01523", Time = "Lifetime", Day = nil, Key = "DYHUB-JL1K9-I2LRG-Y1JA6-P1MA5-LIFETIME" },
    ["mainaccount565535"] = { Tag = "whydowelivelikethis", Time = "Lifetime", Day = nil, Key = "DYHUB-BK0L4-PNJ7B-T6BQ4-U8MA6-LIFETIME" },
    ["gg51213"] = { Tag = "rabbit6715", Time = "Lifetime", Day = nil, Key = "DYHUB-ER3HA-G5BA6-I2M7N-6P8MQ-LIFETIME" },
    ["lw6bh0l"] = { Tag = "chuy_1399999999999999", Time = "Lifetime", Day = nil, Key = "DYHUB-ER3HA-G2BA6-I2M7N-6P8MQ-LIFETIME" },
    ["Tonubaby01"] = { Tag = "kittisak_revar", Time = "Lifetime", Day = nil, Key = "DYHUB-ER3HA-G8BA6-I2M7N-6P2MQ-LIFETIME" },
    ["SoSleepy_Zzp"] = { Tag = "padsxz", Time = "Lifetime", Day = nil, Key = "DYHUB-JR3HA-R8BA6-P2M7N-6P2GQ-LIFETIME" },
    ["artile134"] = { Tag = "artileeyyy", Time = "Lifetime", Day = nil, Key = "DYHUB-NR3HA-R8BA6-P2M7N-6P2GQ-LIFETIME" },
    ["Gottidyce5656"] = { Tag = "sososucu", Time = "Lifetime", Day = nil, Key = "DYHUB-NR9HA-R8BA6-P2M7N-6P2GQ-LIFETIME" },
    ["Secanesseon88"] = { Tag = "secaisgod_", Time = "Lifetime", Day = nil, Key = "DYHUB-NR9OA-R8PA6-P2M7N-6P2GQ-LIFETIME" },
    ["SecaIsGod21"] = { Tag = "secaisgod_", Time = "Lifetime", Day = nil, Key = "DYHUB-NR9PA-R8PA6-P2M7N-6P2GQ-LIFETIME" },
    ["Zenithiannn"] = { Tag = "rroyco_", Time = "Lifetime", Day = nil, Key = "DYHUB-NR9PA-R7PA6-P2M7N-6P9GQ-LIFETIME" },
    ["ifkjtvb"] = { Tag = "scp06469", Time = "Lifetime", Day = nil, Key = "DYHUB-NS5PA-R2PA6-P2M7N-6P9GQ-LIFETIME" },
    ["marktii093114"] = { Tag = "bastepanon", Time = "Lifetime", Day = nil, Key = "DYHUB-NS9PA-R6PA6-P2M7N-6J9GQ-LIFETIME" },
    ["ANJELHD12345"] = { Tag = "nose._._.", Time = "Lifetime", Day = nil, Key = "DYHUB-NS7PA-R6PA6-P2M7N-6J9GQ-LIFETIME" },
    ["HungryAdito"] = { Tag = "hungryadito", Time = "Lifetime", Day = nil, Key = "DYHUB-NS0PA-R6PA6-P2M7N-6J9GQ-LIFETIME" },
    ["XxjackthekolaXx"] = { Tag = "davinhanslie_87731", Time = "Lifetime", Day = nil, Key = "DYHUB-NS9KL-R6PA9-P2M7N-6J9GQ-LIFETIME" },
    ["Yessir_9273"] = { Tag = "wowzer_wowzer", Time = "Lifetime", Day = nil, Key = "DYHUB-NS9KP-R6PA9-P2M7N-6J9GQ-LIFETIME" },
    ["chokun30us"] = { Tag = "chok2391", Time = "Lifetime", Day = nil, Key = "DYHUB-NG9KL-R6PA9-P2M9N-6J9GQ-LIFETIME" },
    ["KanatoKaito"] = { Tag = "novatester7005", Time = "Lifetime", Day = nil, Key = "DYHUB-NL9KL-R6PA9-P2M9N-6J9OQ-LIFETIME" },
    ["flespos83"] = { Tag = "flespos83", Time = "Lifetime", Day = nil, Key = "DYHUB-PL9KL-R6PA9-P2M9N-6J9OQ-LIFETIME" },
    
    -- ====================== YOUTUBE =============================
    ["growwltokens1"] = { Tag = "growwltoken", Time = "Lifetime", Day = nil, Key = "DYHUB-SINISTER" },
    ["Briwbou"] = { Tag = "kumi5002", Time = "Lifetime", Day = nil, Key = "DYHUB-Holiger" },
    ["growwltoken11"] = { Tag = "growwltoken", Time = "Lifetime", Day = nil, Key = "DYHUB-SINISTER-ALT" },
  
    -- ====================== Buyer (Trial / Short-term) =============================
    ["dzibak211122"] = { Tag = "patryk211122", Time = nil, Day = 2, Key = "DYHUB-E1P8A-KEY1DAY" }, 
    ["yantotiw"] = { Tag = "ikyy_maybe", Time = nil, Day = 3, Key = "DYHUB-E4D8A-KEY1DAY" }, 
    ["DANZY259"] = { Tag = "kenbaik", Time = nil, Day = 3, Key = "DYHUB-E4J8A-KEY3DAY" }, 

    ["The_Baconx83"] = { Tag = "Popcat", Time = nil, Day = 1, Key = "DYHUB-FK8HO-KEY1DAY" }, -- today
    ["airat_1433"] = { Tag = "thor074500", Time = nil, Day = 2, Key = "DYHUB-FL3HO-KEY1DAY" }, -- today
    ["akakakakaka201"] = { Tag = "optimus14232", Time = nil, Day = 3, Key = "DYHUB-FI8HO-KEY1DAY" }, -- today
    ["astro_alt113"] = { Tag = "uttvmainer_xd", Time = nil, Day = 7, Key = "DYHUB-D18HO-KEY7DAY" }, -- today
    ["otpremnafh"] = { Tag = "vxh568", Time = nil, Day = 7, Key = "DYHUB-D18VO-KEY7DAY" }, -- today
    ["TBC_GodZero"] = { Tag = "lyagush2952_15020", Time = nil, Day = 4, Key = "DYHUB-D18HO-KEY4DAY" }, -- today
  
    ["Godeater12231"] = { Tag = "rexstorm_", Time = nil, Day = 8, Key = "DYHUB-TL3HO-KEY7DAY" },
 
    ["EVER240284"] = { Tag = "ever2106", Time = nil, Day = 9, Key = "DYHUB-L3PGA-KEY1DAY" },
    ["bojesSinaga"] = { Tag = "bojessinaga", Time = nil, Day = 4, Key = "DYHUB-G8P1L-KEY3DAY" },
    ["Bisa9grg"] = { Tag = "samlovescats_1", Time = nil, Day = 4, Key = "DYHUB-G1P5L-KEY3DAY" },
    ["unfanmasdetsb0"] = { Tag = "holas0467", Time = nil, Day = 4, Key = "DYHUB-G8O1L-KEY3DAY" },

    ["sosomysoso"] = { Tag = "dafik34_84007", Time = nil, Day = 15, Key = "DYHUB-LUNNY-KEY7DAY" },
    ["acengsniper"] = { Tag = "manskiw", Time = nil, Day = 15, Key = "DYHUB-M6BA3-KEY14DAY" },
    ["Its_MortalFTW"] = { Tag = "knaya.", Time = nil, Day = 10, Key = "DYHUB-T5BA3-KEY7DAY" },
    ["roblox_user_7789134494"] = { Tag = "seca._", Time = nil, Day = 35, Key = "DYHUB-YP4A3-KEY34DAY" },
    ["Kazorebere231"] = { Tag = "dyumraisgoodguy", Time = nil, Day = 1000, Key = "DYHUB-IDK" },
    ["gtyyuirtywh"] = { Tag = "yetiyet95yt", Time = nil, Day = 25, Key = "DYHUB-L8MRG-KEY24DAY" },
      
    -- ====================== Booster ==============================
    ["s1ckcvlt"] = { Tag = "jeje", Time = nil, Day = 14, Key = "DYHUB-MPO3Q-KEYBOOSTER" },
    ["andrew_e108"] = { Tag = "andrewsigma345", Time = nil, Day = 14, Key = "DYHUB-MLA3Q-KEYBOOSTER" },
    ["joohnddooee"] = { Tag = "terrufy", Time = nil, Day = 14, Key = "DYHUB-MKA3Q-KEYBOOSTER" },
    ["Sazonhiatt26112"] = { Tag = "basmysad", Time = nil, Day = 25, Key = "DYHUB-MKA3Q-KEYBOOSTER" },
    ["ARTURE210"] = { Tag = "qronzai_", Time = nil, Day = 15, Key = "DYHUB-H6APQ-KEYBOOSTER" },
    ["ZanID25"] = { Tag = "justtforfunnn", Time = nil, Day = 20, Key = "DYHUB-H9MM6-KEYBOOSTER" },
    ["BingoEscapes"] = { Tag = "kxnzozar", Time = nil, Day = 9, Key = "DYHUB-P1MA6-KEYBOOSTER" },
    ["Kindreth_OB0b92S"] = { Tag = "yai2thosewyoknow", Time = nil, Day = 29, Key = "DYHUB-MKA2Q-KEYBOOSTER" },
    ["Alexd100bru"] = { Tag = "olivia_not_fors.", Time = nil, Day = 15, Key = "DYHUB-L9MA6-KEYBOOSTER" },
    ["Lethal_dealh"] = { Tag = "xourlyrics", Time = nil, Day = 15, Key = "DYHUB-H9MA6-KEYBOOSTER" },
    ["Catlinns"] = { Tag = "japonbaligi", Time = nil, Day = 15, Key = "DYHUB-K7NA5-KEYBOOSTER" },
    ["Axe23cap"] = { Tag = "axe23cap", Time = nil, Day = 15, Key = "DYHUB-K7NF5-KEYBOOSTER" },
    ["BVIWWF"] = { Tag = "smi.fi", Time = nil, Day = 15, Key = "DYHUB-F9Q2I-KEYBOOSTER" },
    ["Yuchi_ksm"] = { Tag = "wansao0124", Time = nil, Day = 9, Key = "DYHUB-D2Q2I-KEYBOOSTER" },
    ["Dig1talxkz"] = { Tag = "digital_xkz", Time = nil, Day = 9, Key = "DYHUB-M2G3Q-KEYBOOSTER" },
    ["ClayAltAccount6"] = { Tag = "dejavu_lost", Time = nil, Day = 15, Key = "DYHUB-H8AKQ-KEYBOOSTER" },
    ["SANS8_UJD"] = { Tag = "reimur_rin", Time = nil, Day = 3, Key = "DYHUB-D2Q9I-KEYBOOSTER" },
    ["reilin_26"] = { Tag = "_____p2", Time = nil, Day = 14, Key = "DYHUB-MKA9Q-KEYBOOSTER" },
    ["balle0704"] = { Tag = "beton.zip", Time = nil, Day = 7, Key = "DYHUB-SKA9Q-KEYBOOSTER" },
    ["player19127"] = { Tag = "nooby_19127", Time = nil, Day = 3, Key = "DYHUB-V6NA4-KEYBOOSTER" },
    
    -- ====================== Giveaway =============================
    ["Solvrynnn2"] = { Tag = "solvrynnn", Time = nil, Day = 15, Key = "DYHUB-K8MA3-H7NA4-KEY14DAY" },
    ["Pipahaha13"] = { Tag = "electitous142", Time = nil, Day = 39, Key = "DYHUB-E4Q5W-H7NA4-KEY38DAY" },
    ["WindShootCSGO"] = { Tag = "doquagningg", Time = nil, Day = 39, Key = "DYHUB-A4CQ5-H7NA4-KEY38DAY" },
    ["kikoman714"] = { Tag = "fanluser", Time = nil, Day = 39, Key = "DYHUB-P9MA6-N6HQ5-KEY38DAY" },
    
    ["ChuBinyeuBread"] = { Tag = "gojo_senpai9115", Time = nil, Day = 3, Key = "DYHUB-HPMA6-N6HQ6-KEY3DAY" },

    ["christopherbumitokfc"] = { Tag = "hailsin", Time = nil, Day = 14, Key = "DYHUB-T9PA6-N6HQ5-GIVEAWAY" },
    ["ytalo1500"] = { Tag = "ytalo__", Time = nil, Day = 14, Key = "DYHUB-T9MA6-N6HQ5-GIVEAWAY" },
    ["Zyxnn_18"] = { Tag = "keiii0906", Time = nil, Day = 14, Key = "DYHUB-K9MA6-N6HQ5-GIVEAWAY" },
    ["Parbal_god"] = { Tag = "gorill_guy", Time = nil, Day = 30, Key = "DYHUB-H9MA6-N6HQ5-GIVEAWAY" },
    ["johnnn2013"] = { Tag = "sunni_destroyer", Time = nil, Day = 30, Key = "DYHUB-M9MA6-N6HQ5-GIVEAWAY" },
    ["farull6"] = { Tag = "jstnewflf_55559", Time = "Lifetime", Day = nil, Key = "DYHUB-F9MA6-N6HQ5-GIVEAWAY" },
    ["ehejshehehs1"] = { Tag = "firejason1fi1", Time = nil, Day = 14, Key = "DYHUB-E9RA6-N6HQ5-GIVEAWAY" },
    ["topoyoo3"] = { Tag = "afdangimang0507", Time = nil, Day = 14, Key = "DYHUB-T9HA6-N6HQ5-GIVEAWAY" },
    ["uhhMeSksm"] = { Tag = "sksmcutg", Time = nil, Day = 30, Key = "DYHUB-P9MA6-N6OQ5-GIVEAWAY" },
    ["roblox"] = { Tag = "roblox", Time = nil, Day = 39, Key = "DYHUB-D6MA6-N6HQ5-GIVEAWAY" },
    
    -- ====================== BUY TH =============================
    ["NoN_oj1"] = { Tag = "xeqes", Time = "Lifetime", Day = nil, Key = "DYHUB-D4QF3-TQ6HL-LQ8V4-BA5GQ-LIFETIME" },
    ["GODxGSP"] = { Tag = "k7nzz_", Time = "Lifetime", Day = nil, Key = "DYHUB-F4VA5-TQ6HL-LQ8V4-BA5GQ-LIFETIME" },

    -- ====================== PAYMENT =============================
    ["Oegsjmc"] = { Tag = "topnumberone.", Time = nil, Day = 177, Key = "DYHUB-SNOWY-KEYHELPER" },
    ["monyegaming24"] = { Tag = "whitecat1_", Time = nil, Day = 8, Key = "DYHUB-K6VA5-TRIALHELPER" },
    ["parbal_god"] = { Tag = "gorill_guy", Time = nil, Day = 15, Key = "DYHUB-F4VA5-HELPER" },
    ["pipahaha13"] = { Tag = "lingabool", Time = nil, Day = 8, Key = "DYHUB-F4J8L-TRIALHELPER" },
    ["heavenssag1"] = { Tag = "vestode", Time = nil, Day = 9, Key = "DYHUB-K6VP5-TRIALHELPER" },
    ["ILO576"] = { Tag = "vestode", Time = nil, Day = 8, Key = "DYHUB-K6V95-TRIALHELPER" },
    ["zeus15792"] = { Tag = "bajjoss", Time = nil, Day = 8, Key = "DYHUB-J6MA5-TRIALHELPER" },
}
